import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// Theme provider
import { ThemeProvider } from "@/components/theme-provider"
// Shad-cn comps
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import Navbar from "@/components/navbar";
import { ThemeToggle } from "@/components/theme-toggle";
// Styles
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col">
            {/* <Navbar /> */}
            <main className="">
              <SidebarProvider>
                <AppSidebar />
                <SidebarTrigger />
                <ThemeToggle />
                {children}
              </SidebarProvider>
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html >
  );
}
